apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/gregkroon/gitopsflow.git
        revision: HEAD
        files:
          - path: "cluster-config/*/config.json"
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.out-of-sync.harness: ""
      name: '{{cluster_name}}-guestbook'
      labels:
        harness.io/envRef: '{{environment}}-'
        harness.io.serviceRef: '{{harness_service}}'
        harness.io/buildRef: somevalue
    spec:
      project: 5b758ebb
      source:
        repoURL: https://github.com/gregkroon/gitopsflow.git
        targetRevision: HEAD
        path: "base"
        kustomize:
          images:
            - name: munkys123/guestbook
              newTag: somevalue
      destination:
        server: '{{server_address}}'
        namespace: 'guestbook-{{environment}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
